engines:
  eslint:
    enabled: true
    channel: "eslint-3"
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - lib/**
  - packages/*/lib/**
exclude_paths:
- "**/fixtures/**/*"
